# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='fabricator',
            field=models.CharField(default='-', max_length=30),
        ),
    ]
