# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 15:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_clients'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='clients',
            new_name='client',
        ),
    ]
