# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-11 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_auto_20160818_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='equipment',
        ),
        migrations.AddField(
            model_name='equipment',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storage.Assignment'),
        ),
    ]
