# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-16 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_auto_20160911_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='Type',
            field=models.CharField(choices=[('R', 'Rental'), ('FS', 'Full Service')], default='Rental', max_length=2),
        ),
    ]
