# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-16 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_assignment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
