# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-01 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0008_equipment_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='number',
        ),
        migrations.AddField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[(b'R', b'Geladen'), (b'IS', b'Im Lager')], default='IS', max_length=1),
        ),
    ]
