# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-01 13:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0009_auto_20161001_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='status',
        ),
    ]
