# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-20 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0010_remove_equipment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='event',
        ),
        migrations.AddField(
            model_name='equipment',
            name='event',
            field=models.ManyToManyField(blank=True, to='storage.Assignment'),
        ),
    ]
