# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-23 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0011_auto_20161020_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='avail_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='equipment',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
