# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-23 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0012_auto_20161023_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Used_quantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_quantity', models.PositiveIntegerField(default=0)),
                ('assignment', models.ManyToManyField(blank=True, to='storage.Assignment')),
            ],
        ),
        migrations.AlterField(
            model_name='equipment',
            name='avail_quantity',
            field=models.PositiveIntegerField(default=models.PositiveIntegerField(default=1)),
        ),
        migrations.AddField(
            model_name='used_quantity',
            name='equipment',
            field=models.ManyToManyField(blank=True, to='storage.Equipment'),
        ),
    ]
