# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-23 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0013_auto_20161023_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='avail_quantity',
            field=models.IntegerField(default=models.IntegerField(default=1)),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='used_quantity',
            name='equipment',
            field=models.ManyToManyField(blank=True, to='storage.Equipment'),
        ),
    ]
