# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-23 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0014_auto_20161023_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='used_quantity',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='used_quantity',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='avail_quantity',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='quantity',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.DeleteModel(
            name='Used_quantity',
        ),
    ]
