# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-26 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0015_auto_20161023_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='Used_quantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_quantity', models.PositiveIntegerField(default=0)),
                ('assignment', models.ManyToManyField(blank=True, to='storage.Assignment')),
                ('equipment', models.ManyToManyField(blank=True, to='storage.Equipment')),
            ],
        ),
    ]
