# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-26 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0016_used_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='used_quantity',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='used_quantity',
            name='equipment',
        ),
        migrations.AddField(
            model_name='equipment',
            name='used_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.DeleteModel(
            name='Used_quantity',
        ),
    ]
