# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-26 19:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0017_auto_20161026_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='used_quantity',
        ),
    ]
