# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-04 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0019_auto_20161104_0723'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Used_quantity',
            new_name='AssignmentQuantity',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='equipment_quantity',
        ),
        migrations.RemoveField(
            model_name='assignmentquantity',
            name='equipment',
        ),
        migrations.AddField(
            model_name='assignmentquantity',
            name='assignment',
            field=models.ManyToManyField(blank=True, to='storage.Assignment'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='UsedQuantity',
            field=models.ManyToManyField(blank=True, to='storage.AssignmentQuantity'),
        ),
    ]
